name=SamsungNASA_AVR
version=1.1.0
author=Németh Bálint
maintainer=Németh Bálint
sentence=Samsung NASA protocol implementation for Arduino AVR. (SamsungNASA)
paragraph=Samsung NASA protocol library with RS485 support. Arduino AVR optimized version with no dynamic memory allocation, synchronous polling, and low memory footprint.
category=Communication
url=https://github.com/Aranyalma2/SamsungNASA-AVR
architectures=avr,esp32,esp8266
includes=SamsungNASA_AVR.h